import { InventoryItem } from '../types';

export const INITIAL_CLEANING_INVENTORY: Omit<InventoryItem, 'tenantId'>[] = [
  {
    id: 'insumo_papel_higienico',
    name: 'Papel Higiénico',
    category: 'Limpieza y Baño',
    unit: 'Rollos',
    currentStock: 11,
    minStock: 4,
    details: '300 mts / 1 Bolsa (8) + 2 Sueltos',
    lastPurchaseDate: '2026-07-10',
    lastPurchaseCost: 21696,
    lastPurchaseQuantity: '2 rollos 300m',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'insumo_toallas_intercaladas',
    name: 'Toallas Intercaladas Beige',
    category: 'Limpieza y Baño',
    unit: 'Cajas',
    currentStock: 2,
    minStock: 1,
    details: 'Caja x 2000 unidades',
    lastPurchaseDate: '2026-07-10',
    lastPurchaseCost: 20230,
    lastPurchaseQuantity: '1 caja x 2000',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'insumo_rollo_papel_bobina',
    name: 'Rollo papel (Bobina)',
    category: 'Descartables',
    unit: 'Rollos',
    currentStock: 2,
    minStock: 2,
    details: '200m / Bolsas de 4 rollos de 200m',
    lastPurchaseDate: '2026-07-10',
    lastPurchaseCost: 131196,
    lastPurchaseQuantity: '6 bolsas (4 rollos c/u)',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'insumo_bolsas_arranque',
    name: 'Bolsas de arranque',
    category: 'Descartables',
    unit: 'Rollos',
    currentStock: 2,
    minStock: 1,
    details: 'Medidas 30x40 / 40x50 (600 grs)',
    lastPurchaseDate: '2026-07-10',
    lastPurchaseCost: 25380,
    lastPurchaseQuantity: '3 rollos',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'insumo_bolsas_residuos',
    name: 'Bolsas residuos',
    category: 'Limpieza General',
    unit: 'Paquetes',
    currentStock: 4,
    minStock: 2,
    details: 'Medida 45x60 (Paquetes de 30/90 bolsas)',
    lastPurchaseDate: '2026-07-10',
    lastPurchaseCost: 5304,
    lastPurchaseQuantity: '6 paquetes',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'insumo_bicarbonato',
    name: 'Bicarbonato de Sodio',
    category: 'Limpieza General',
    unit: 'Bolsas',
    currentStock: 1,
    minStock: 1,
    details: 'Bolsa de 1 KG',
    lastPurchaseDate: '2026-04-10',
    lastPurchaseCost: 0,
    lastPurchaseQuantity: '1 bolsa x 1kg',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'insumo_jabon_liquido',
    name: 'Jabón Líquido para Manos',
    category: 'Higiene Personal',
    unit: 'Bidones',
    currentStock: 2,
    minStock: 1,
    details: 'Bidón de 5 Litros',
    lastPurchaseDate: '2026-02-18',
    lastPurchaseCost: 0,
    lastPurchaseQuantity: 'Bidón 5L',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'insumo_aromatizante',
    name: 'Aromatizante de Ambiente',
    category: 'Limpieza y Baño',
    unit: 'Aerosoles',
    currentStock: 2,
    minStock: 1,
    details: 'Aerosol repuesto / gatillo',
    lastPurchaseDate: '2026-07-10',
    lastPurchaseCost: 11584,
    lastPurchaseQuantity: '2 aerosoles',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'insumo_detergente',
    name: 'Detergente Vajilla',
    category: 'Limpieza y Cocina',
    unit: 'Botellas',
    currentStock: 1,
    minStock: 1,
    details: 'Botella de 500 ml',
    lastPurchaseDate: '2026-02-18',
    lastPurchaseCost: 5080,
    lastPurchaseQuantity: '1 botella x 500ml',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'insumo_alcohol_70_30',
    name: 'Alcohol 70/30 Sanitizante',
    category: 'Desinfección y Kinesiología',
    unit: 'Bidones',
    currentStock: 1.5,
    minStock: 1,
    details: 'Bidón de 5 Litros diluido al 70%',
    lastPurchaseDate: '2026-04-10',
    lastPurchaseCost: 0,
    lastPurchaseQuantity: 'Bidón 5L',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'insumo_cloro',
    name: 'Cloro Concentrado',
    category: 'Limpieza y Desinfección',
    unit: 'Bidones',
    currentStock: 1,
    minStock: 1,
    details: 'Bidón de 5 Litros',
    lastPurchaseDate: '2026-02-18',
    lastPurchaseCost: 0,
    lastPurchaseQuantity: '1 bidón x 5L',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'insumo_lavandina_gel',
    name: 'Lavandina en Gel',
    category: 'Limpieza y Baño',
    unit: 'Botellas',
    currentStock: 2,
    minStock: 1,
    details: 'Botella de 700 ml',
    lastPurchaseDate: '2026-07-10',
    lastPurchaseCost: 4044,
    lastPurchaseQuantity: '1 botella x 700ml',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'insumo_perfumina_pisos',
    name: 'Perfumina para Pisos',
    category: 'Limpieza General',
    unit: 'Bidones',
    currentStock: 2.5,
    minStock: 1,
    details: 'Bidón de 5 Litros concentrado',
    lastPurchaseDate: '2026-02-18',
    lastPurchaseCost: 2340,
    lastPurchaseQuantity: '1 bidón x 5L',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'insumo_vinagre_alcohol',
    name: 'Vinagre de Alcohol',
    category: 'Limpieza General',
    unit: 'Botellas',
    currentStock: 1,
    minStock: 1,
    details: 'Botella de 4,5 Litros',
    lastPurchaseDate: '2026-07-10',
    lastPurchaseCost: 6304,
    lastPurchaseQuantity: '1 botella x 4.5L',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'insumo_trapo_microfibra',
    name: 'Trapo de Cocina / Microfibra',
    category: 'Limpieza y Cocina',
    unit: 'Unidades',
    currentStock: 3,
    minStock: 1,
    details: 'Paño de microfibra multiuso',
    lastPurchaseDate: '2026-02-18',
    lastPurchaseCost: 5796,
    lastPurchaseQuantity: '3 unidades',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'insumo_escobilla_bano',
    name: 'Escobilla de Baño',
    category: 'Limpieza y Baño',
    unit: 'Unidades',
    currentStock: 2,
    minStock: 1,
    details: 'Escobilla con soporte plástico',
    lastPurchaseDate: '2026-02-18',
    lastPurchaseCost: 8640,
    lastPurchaseQuantity: '2 unidades',
    updatedAt: new Date().toISOString()
  },
  {
    id: 'insumo_quita_sarro',
    name: 'Quita Sarro',
    category: 'Limpieza y Baño',
    unit: 'Botellas',
    currentStock: 1,
    minStock: 1,
    details: 'Botella de 1 Litro',
    lastPurchaseDate: '2026-07-10',
    lastPurchaseCost: 4020,
    lastPurchaseQuantity: '1 botella x 1L',
    updatedAt: new Date().toISOString()
  }
];
